    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - name: MongoDB in GitHub Actions
            uses: supercharge/mongodb-github-action@1.1.0
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
            env:
              DB_URL: localhost:27017/record-shop
              DB_USER: root
              DB_PASSWORD: none
